### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mansisindhu** [meesahil7/urban-service#36]
- After selecting on city it’s throwing 404 page, unable to see any feature or service
- UI is breaking in many places
- Images are shrinking in landing page and other places
- Website is not responsive
- After login still can see the login modal, this should not be happening
- Functionality and logic is lacking
- Unnecessary consoles

**Comment by meesahil7** [comment]
- [ ] Removed unnecessary consoles
- [ ] Login modal issue resolved
- [ ] 404 error after selecting city is now resolved

**Comment by meesahil7** [comment]
- [ ] Fixed cart logic
- [ ] Resolved location setup
